# For more information: https://laravel.com/docs/sail
version: '3'

services:
    phpmyadmin:
        image: phpmyadmin:5.1.1-apache
        ports:
            - 8100:80
        environment:
            MYSQL_ROOT_PASSWORD: 'masumi'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'masumi'
            PMA_HOST: mysql
        depends_on:
            - mysql
        networks:
            - fastify

    mysql:
        image: 'mysql:5.7.34'
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: 'masumi'
            MYSQL_DATABASE: 'fastify'
            MYSQL_USER: 'masum'
            MYSQL_PASSWORD: 'masumi'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './database:/var/lib/mysql'
        networks:
            - fastify

networks:
    fastify: